// Generated by gencpp from file sine_wave/MultTwoFloatsResponse.msg
// DO NOT EDIT!


#ifndef SINE_WAVE_MESSAGE_MULTTWOFLOATSRESPONSE_H
#define SINE_WAVE_MESSAGE_MULTTWOFLOATSRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace sine_wave
{
template <class ContainerAllocator>
struct MultTwoFloatsResponse_
{
  typedef MultTwoFloatsResponse_<ContainerAllocator> Type;

  MultTwoFloatsResponse_()
    : result(0.0)  {
    }
  MultTwoFloatsResponse_(const ContainerAllocator& _alloc)
    : result(0.0)  {
  (void)_alloc;
    }



   typedef float _result_type;
  _result_type result;





  typedef boost::shared_ptr< ::sine_wave::MultTwoFloatsResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::sine_wave::MultTwoFloatsResponse_<ContainerAllocator> const> ConstPtr;

}; // struct MultTwoFloatsResponse_

typedef ::sine_wave::MultTwoFloatsResponse_<std::allocator<void> > MultTwoFloatsResponse;

typedef boost::shared_ptr< ::sine_wave::MultTwoFloatsResponse > MultTwoFloatsResponsePtr;
typedef boost::shared_ptr< ::sine_wave::MultTwoFloatsResponse const> MultTwoFloatsResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::sine_wave::MultTwoFloatsResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::sine_wave::MultTwoFloatsResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace sine_wave

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/melodic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::sine_wave::MultTwoFloatsResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::sine_wave::MultTwoFloatsResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::sine_wave::MultTwoFloatsResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::sine_wave::MultTwoFloatsResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::sine_wave::MultTwoFloatsResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::sine_wave::MultTwoFloatsResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::sine_wave::MultTwoFloatsResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "db954e5de3aba73b237d07575e5cac28";
  }

  static const char* value(const ::sine_wave::MultTwoFloatsResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xdb954e5de3aba73bULL;
  static const uint64_t static_value2 = 0x237d07575e5cac28ULL;
};

template<class ContainerAllocator>
struct DataType< ::sine_wave::MultTwoFloatsResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "sine_wave/MultTwoFloatsResponse";
  }

  static const char* value(const ::sine_wave::MultTwoFloatsResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::sine_wave::MultTwoFloatsResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float32 result\n\
\n\
";
  }

  static const char* value(const ::sine_wave::MultTwoFloatsResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::sine_wave::MultTwoFloatsResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.result);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct MultTwoFloatsResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::sine_wave::MultTwoFloatsResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::sine_wave::MultTwoFloatsResponse_<ContainerAllocator>& v)
  {
    s << indent << "result: ";
    Printer<float>::stream(s, indent + "  ", v.result);
  }
};

} // namespace message_operations
} // namespace ros

#endif // SINE_WAVE_MESSAGE_MULTTWOFLOATSRESPONSE_H
