// Generated by gencpp from file service_demo/AddTwoInts.msg
// DO NOT EDIT!


#ifndef SERVICE_DEMO_MESSAGE_ADDTWOINTS_H
#define SERVICE_DEMO_MESSAGE_ADDTWOINTS_H

#include <ros/service_traits.h>


#include <service_demo/AddTwoIntsRequest.h>
#include <service_demo/AddTwoIntsResponse.h>


namespace service_demo
{

struct AddTwoInts
{

typedef AddTwoIntsRequest Request;
typedef AddTwoIntsResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct AddTwoInts
} // namespace service_demo


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::service_demo::AddTwoInts > {
  static const char* value()
  {
    return "6a2e34150c00229791cc89ff309fff21";
  }

  static const char* value(const ::service_demo::AddTwoInts&) { return value(); }
};

template<>
struct DataType< ::service_demo::AddTwoInts > {
  static const char* value()
  {
    return "service_demo/AddTwoInts";
  }

  static const char* value(const ::service_demo::AddTwoInts&) { return value(); }
};


// service_traits::MD5Sum< ::service_demo::AddTwoIntsRequest> should match 
// service_traits::MD5Sum< ::service_demo::AddTwoInts > 
template<>
struct MD5Sum< ::service_demo::AddTwoIntsRequest>
{
  static const char* value()
  {
    return MD5Sum< ::service_demo::AddTwoInts >::value();
  }
  static const char* value(const ::service_demo::AddTwoIntsRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::service_demo::AddTwoIntsRequest> should match 
// service_traits::DataType< ::service_demo::AddTwoInts > 
template<>
struct DataType< ::service_demo::AddTwoIntsRequest>
{
  static const char* value()
  {
    return DataType< ::service_demo::AddTwoInts >::value();
  }
  static const char* value(const ::service_demo::AddTwoIntsRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::service_demo::AddTwoIntsResponse> should match 
// service_traits::MD5Sum< ::service_demo::AddTwoInts > 
template<>
struct MD5Sum< ::service_demo::AddTwoIntsResponse>
{
  static const char* value()
  {
    return MD5Sum< ::service_demo::AddTwoInts >::value();
  }
  static const char* value(const ::service_demo::AddTwoIntsResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::service_demo::AddTwoIntsResponse> should match 
// service_traits::DataType< ::service_demo::AddTwoInts > 
template<>
struct DataType< ::service_demo::AddTwoIntsResponse>
{
  static const char* value()
  {
    return DataType< ::service_demo::AddTwoInts >::value();
  }
  static const char* value(const ::service_demo::AddTwoIntsResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // SERVICE_DEMO_MESSAGE_ADDTWOINTS_H
